function [RHS] = kExplicitRHSke(Geometry, k, eps, i, j, xnodel, ynodel, ...
    dxblock, dyblock, mutc, mueffcSigK, rhoc, u, v, N_xtot, N_ytot)
    %RHS of k-equation!!

    %k.1) Transport of k by Convection!
    %Central differencing of source terms eddy viscosity.
    dmudx = (mueffcSigK(i+1,j) - mueffcSigK(i-1,j))/...
        (xnodel(i+1,j) - xnodel(i-1,j));
    dmudy = (mueffcSigK(i,j+1) - mueffcSigK(i,j-1))/...
        (ynodel(i,j+1) - ynodel(i,j-1));

    Fkconv = 3; %1) Central differencing 2) 1st-order upwind
    %             3) 2nd-order upwind for convection term
    switch Fkconv
        case 1 %Transport of k by convection - Central differencing
            Conv_kx = (k(i+1,j)-k(i-1,j))/...
                (xnodel(i+1,j)-xnodel(i-1,j))*(u(i-1,j)+u(i,j))/2;
            Conv_ky = (k(i,j+1)-k(i,j-1))/...
                (ynodel(i,j+1)-ynodel(i,j-1))*(v(i,j)+v(i,j-1))/2;
        case 2 %Transport of k by convection - First-Order Upwind
            if((u(i,j) + u(i-1,j))/2 > 0)
                Conv_kx = (k(i,j) - k(i-1,j))/...
                    (xnodel(i,j)-xnodel(i-1,j))*(u(i,j)+u(i-1,j))/2;
            else
                Conv_kx = (k(i+1,j)-k(i,j))/...
                    (xnodel(i+1,j)-xnodel(i,j))*(u(i-1,j)+u(i,j))/2;
            end

            if((v(i,j) + v(i,j-1))/2 > 0)
                Conv_ky = (k(i,j) - k(i,j-1))/...
                    (ynodel(i,j)-ynodel(i,j-1))*(v(i,j)+v(i,j-1))/2;
            else
                Conv_ky = (k(i,j+1)-k(i,j))/...
                    (ynodel(i,j+1)-ynodel(i,j))*(v(i,j)+v(i,j-1))/2;
            end
        case 3 %Transport of k by convection - Second-Order Upwind
            if((u(i,j) + u(i-1,j))/2 > 0)
                if(i == 2)
                    Conv_kx = (k(i,j) - k(i-1,j))/...
                        (xnodel(i,j)-xnodel(i-1,j))*(u(i,j)+u(i-1,j))/2;
                else
                    Conv_kx = (3*k(i,j) - 4*k(i-1,j) + k(i-2,j))/...
                        (xnodel(i,j)-xnodel(i-2,j))*(u(i,j)+u(i-1,j))/2;
                end
            else
                if(i == N_xtot-1)
                    Conv_kx = (k(i+1,j) - k(i,j))/...
                        (xnodel(i+1,j)-xnodel(i,j))*(u(i,j)+u(i-1,j))/2;
                else
                    Conv_kx = (-3*k(i,j) + 4*k(i+1,j) - k(i+2,j))/...
                        (xnodel(i+2,j)-xnodel(i,j))*(u(i,j)+u(i-1,j))/2;
                end
            end

            if((v(i,j) + v(i,j-1))/2 > 0)
                if(j == 2)
                    Conv_ky = (k(i,j) - k(i,j-1))/...
                        (ynodel(i,j)-ynodel(i,j-1))*(v(i,j)+v(i,j-1))/2;
                else
                    Conv_ky = (3*k(i,j) - 4*k(i,j-1) + k(i,j-2))/...
                        (ynodel(i,j)-ynodel(i,j-2))*(v(i,j)+v(i,j-1))/2;
                end
            else
                if(j == N_ytot-1)
                    Conv_ky = (k(i,j+1) - k(i,j))/...
                        (ynodel(i,j+1)-ynodel(i,j))*(v(i,j)+v(i,j-1))/2;
                else
                    Conv_ky = (-3*k(i,j) + 4*k(i,j+1) - k(i,j+2))/...
                        (ynodel(i,j+2)-ynodel(i,j))*(v(i,j)+v(i,j-1))/2;
                end
            end
    end
    
    Sourcemux = 0; Sourcemuy = 0;
%     %Source term effective viscosity sig k
%     if(dmudx/rhoc > 0)
%         Sourcemux = (k(i,j) - k(i-1,j))/...
%             (xnodel(i,j)-xnodel(i-1,j))*dmudx/rhoc;
%     else
%         Sourcemux = (k(i+1,j) - k(i,j))/...
%             (xnodel(i+1,j)-xnodel(i,j))*dmudx/rhoc;
%     end
% 
%     if(dmudy/rhoc > 0)
%         Sourcemuy = (k(i,j) - k(i,j-1))/...
%             (ynodel(i,j)-ynodel(i,j-1))*dmudy/rhoc;
%     else
%         Sourcemuy = (k(i,j+1)-k(i,j))/...
%             (ynodel(i,j+1)-ynodel(i,j))*dmudy/rhoc;
%     end

    %Calculate Rate of strain tensors Sxy = Syx! Symmetrical!
    Sxx = (u(i,j) - u(i-1,j))/dxblock(i,j);
    Syy = (v(i,j) - v(i,j-1))/dyblock(i,j);
    Sxy = 1/2*(   ( 1/2*( (u(i,j+1)*dyblock(i,j)+u(i,j)*dyblock(i,j+1))/...
        (dyblock(i,j+1)+dyblock(i,j)) +...
        (u(i-1,j+1)*dyblock(i,j)+u(i-1,j)*dyblock(i,j+1))/...
        (dyblock(i,j+1)+dyblock(i,j)) ) -...
        1/2*( (u(i,j)*dyblock(i,j-1)+u(i,j-1)*dyblock(i,j))/...
        (dyblock(i,j)+dyblock(i,j-1)) +...
        (u(i-1,j)*dyblock(i,j-1)+u(i-1,j-1)*dyblock(i,j))/...
        (dyblock(i,j)+dyblock(i,j-1)) ) )/dyblock(i,j) +...
        ...
        1/2*( (v(i+1,j)*dxblock(i,j)+v(i,j)*dxblock(i+1,j))/...
        (dxblock(i+1,j)+dxblock(i,j)) +...
        (v(i+1,j-1)*dxblock(i,j) + v(i,j-1)*dxblock(i+1,j))/...
        (dxblock(i+1,j)+dxblock(i,j)) -...
        (v(i,j)*dxblock(i-1,j)+v(i-1,j)*dxblock(i,j))/...
        (dxblock(i,j)+dxblock(i-1,j)) -...
        (v(i,j-1)*dxblock(i-1,j)+v(i-1,j-1)*dxblock(i,j))/...
        (dxblock(i,j)+dxblock(i-1,j)) )/dxblock(i,j)   );

    %k.2) Production rate of k!
    normS = sqrt(2*Sxx^2 + 2*Syy^2 + 4*Sxy^2);
    P_k = mutc(i,j)/rhoc*normS^2;
    
    %k.3) epsilon!
    
    %k.4) Transport of k by diffusion!
    Diff_kx = 1/(rhoc*dxblock(i,j))*...
        ( (mueffcSigK(i+1,j)*dxblock(i,j)+mueffcSigK(i,j)*dxblock(i+1,j))/...
        (dxblock(i+1,j)+dxblock(i,j))*(k(i+1,j)-k(i,j))/(xnodel(i+1,j)-xnodel(i,j)) -...
        (mueffcSigK(i,j)*dxblock(i-1,j)+mueffcSigK(i-1,j)*dxblock(i,j))/...
        (dxblock(i,j)+dxblock(i-1,j))*(k(i,j)-k(i-1,j))/(xnodel(i,j)-xnodel(i-1,j)) );
    Diff_ky = 1/(rhoc*dyblock(i,j))*( (mueffcSigK(i,j+1)*dyblock(i,j)+ ...
        mueffcSigK(i,j)*dyblock(i,j+1))/(dyblock(i,j+1)+dyblock(i,j))*...
        (k(i,j+1)-k(i,j))/(ynodel(i,j+1)-ynodel(i,j)) -...
        (mueffcSigK(i,j)*dyblock(i,j-1)+mueffcSigK(i,j-1)*dyblock(i,j))/...
        (dyblock(i,j)+dyblock(i,j-1))*(k(i,j)-k(i,j-1))/(ynodel(i,j)-ynodel(i,j-1)) );

    %k.5) Axisymmetric source!
    if(Geometry == 2 || Geometry == 3)
        SourceAxiSym = 1/ynodel(i,j)*(mueffcSigK(i,j))/rhoc*...
            (k(i,j+1) - k(i,j-1))/(ynodel(i,j+1)-ynodel(i,j-1));
    else; SourceAxiSym = 0; end;

    %Assembly
    RHS = - Conv_kx - Conv_ky + P_k - eps(i,j) + Diff_kx + Diff_ky + ...
        SourceAxiSym + Sourcemux + Sourcemuy;
end