function [AmatK] = kekAmat(N_xtot, N_ytot, xnodel, ynodel, dxblock, dyblock, ...
    u, v, rhoc, mueffc, TKEold, epsold, dt, jin)
%Set-up k - Amatrix
    AmatK=zeros((N_xtot-2)*(N_ytot-2));

    for i=1:(N_xtot-2)
        for j=1:(N_ytot-2)
            %Diagonal terms for k(i,j) (i+1) (j+1)
            AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) = 1/dt + ...
                1/(rhoc*dxblock(i+1,j+1))*(mueffc(i+2,j+1)*dxblock(i+1,j+1) ...
                + mueffc(i+1,j+1)*dxblock(i+2,j+1))/...
                (dxblock(i+2,j+1)+dxblock(i+1,j+1))/(xnodel(i+2,j+1)-xnodel(i+1,j+1)) ...
                + 1/(rhoc*dxblock(i+1,j+1))*(mueffc(i+1,j+1)*dxblock(i,j+1) + ...
                mueffc(i,j+1)*dxblock(i+1,j+1))/...
                (dxblock(i+1,j+1)+dxblock(i,j+1))/(xnodel(i+1,j+1)-xnodel(i,j+1)) + ...%diffusion x
                1/(rhoc*dyblock(i+1,j+1))*(mueffc(i+1,j+2)*dyblock(i+1,j+1) ...
                + mueffc(i+1,j+1)*dyblock(i+1,j+2))/...
                (dyblock(i+1,j+2)+dyblock(i+1,j+1))/(ynodel(i+1,j+2)-ynodel(i+1,j+1)) + ...
                1/(rhoc*dyblock(i+1,j+1))*(mueffc(i+1,j+1)*dyblock(i+1,j) + ...
                mueffc(i+1,j)*dyblock(i+1,j+1))/...
                (dyblock(i+1,j+1)+dyblock(i+1,j))/(ynodel(i+1,j+1)-ynodel(i+1,j)) + ...%diffusion y
                epsold(i+1,j+1)/TKEold(i+1,j+1) - ... %trick eps = k*eps/k
                ((u(i,j+1)+u(i+1,j+1))/2)/(xnodel(i+2,j+1)-xnodel(i+1,j+1)) - ...
                ((v(i+1,j+1)+v(i+1,j))/2)/(ynodel(i+1,j+2)-ynodel(i+1,j+1)); %1st-order-upwind

            %Implicit BC: k(N_xtot,:) = k(N_xtot-1,:) %checked!
            if(i==(N_xtot-2))
                AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) = ...
                    AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) +...
                    1/(xnodel(i+2,j+1)-xnodel(i+1,j+1))*(u(i,j+1)+u(i+1,j+1))/2 - ... 
                    1/(rhoc*dxblock(i+1,j+1))*(mueffc(i+2,j+1)*dxblock(i+1,j+1) + ...
                    mueffc(i+1,j+1)*dxblock(i+2,j+1))/...
                    (dxblock(i+2,j+1)+dxblock(i+1,j+1))/(xnodel(i+2,j+1)-xnodel(i+1,j+1));
            end

            %Implicit BC: k(1,(jin+1):N_ytot) = - k(2,(jin+1):N_ytot) %checked!
            if(i==1 && j>=jin)
                AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) = ...
                    AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) - ...
                    (- 1/(rhoc*dxblock(i+1,j+1))*...
                    (mueffc(i+1,j+1)*dxblock(i,j+1) + mueffc(i,j+1)*dxblock(i+1,j+1))/...
                    (dxblock(i+1,j+1)+dxblock(i,j+1))/(xnodel(i+1,j+1)-xnodel(i,j+1)) );
            end
            
            %Implicit BC k(1,1:jin) = kinlet in Source Term!

            %Implicit BC: k(:,1) = k(:,2); %checked!
            if(j == 1) 
                AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) = ...
                    AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) +...
                    (-1/(rhoc*dyblock(i+1,j+1))*(mueffc(i+1,j+1)*dyblock(i+1,j) +...
                    mueffc(i+1,j)*dyblock(i+1,j+1))/...
                    (dyblock(i+1,j+1)+dyblock(i+1,j))/(ynodel(i+1,j+1)-ynodel(i+1,j)) );
            end
            
            %Implicit BC: k(:,N_ytot) = - k(:,N_ytot-1) %checked!
            if(j==(N_ytot-2))
                AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) = ...
                    AmatK(i+(j-1)*(N_xtot-2),i+(j-1)*(N_xtot-2)) - ...
                    (1/(ynodel(i+1,j+2)-ynodel(i+1,j+1))*(v(i+1,j+1)+v(i+1,j))/2 - ...
                    1/(rhoc*dyblock(i+1,j+1))*(mueffc(i+1,j+2)*dyblock(i+1,j+1) + ...
                    mueffc(i+1,j+1)*dyblock(i+1,j+2))/...
                    (dyblock(i+1,j+2)+dyblock(i+1,j+1))/(ynodel(i+1,j+2)-ynodel(i+1,j+1)));
            end
        end
    end

    for i=1:(N_xtot-3)
        for j=1:(N_ytot-2)
            %Term for k(i+1,j) %(i+1) (j+1) %checked!
            AmatK(i+(j-1)*(N_xtot-2), i+(j-1)*(N_xtot-2)+1) = ...
                1/(xnodel(i+2,j+1)-xnodel(i+1,j+1))*(u(i,j+1)+u(i+1,j+1))/2 - ...
                1/(rhoc*dxblock(i+1,j+1))*(mueffc(i+2,j+1)*dxblock(i+1,j+1) ...
                + mueffc(i+1,j+1)*dxblock(i+2,j+1))/...
                (dxblock(i+2,j+1)+dxblock(i+1,j+1))/(xnodel(i+2,j+1)-xnodel(i+1,j+1));
            %Term for k(i-1,j) %(i+2) (j+1) %checked!
            AmatK(i+(j-1)*(N_xtot-2)+1, i+(j-1)*(N_xtot-2)) =  ...
                - 1/(rhoc*dxblock(i+2,j+1))*(mueffc(i+2,j+1)*dxblock(i+1,j+1) ...
                + mueffc(i+1,j+1)*dxblock(i+2,j+1))/...
                (dxblock(i+2,j+1)+dxblock(i+1,j+1))/(xnodel(i+2,j+1)-xnodel(i+1,j+1));
        end
    end

    for i=1:(N_xtot-2)
        for j=1:(N_ytot-3)
            %Term for k(i,j+1) (i+1) (j+1) %checked!
            AmatK(i+(j-1)*(N_xtot-2), i+j*(N_xtot-2)) = ...
                1/(ynodel(i+1,j+2)-ynodel(i+1,j+1))*(v(i+1,j+1)+v(i+1,j))/2 - ...
                1/(rhoc*dyblock(i+1,j+1))*(mueffc(i+1,j+2)*dyblock(i+1,j+1) + ...
                mueffc(i+1,j+1)*dyblock(i+1,j+2))/...
                (dyblock(i+1,j+2)+dyblock(i+1,j+1))/(ynodel(i+1,j+2)-ynodel(i+1,j+1));
            %Term for k(i,j-1) (i+1) (j+2) %checked!
            AmatK(i+j*(N_xtot-2), i+(j-1)*(N_xtot-2)) = ...
                - 1/(rhoc*dyblock(i+1,j+2))*(mueffc(i+1,j+2)*dyblock(i+1,j+1) + ...
                mueffc(i+1,j+1)*dyblock(i+1,j+2))/...
                (dyblock(i+1,j+2)+dyblock(i+1,j+1))/(ynodel(i+1,j+2)-ynodel(i+1,j+1));
        end
    end
end