function [STK, Dmat] = keSTK(Geometry, N_xtot, N_ytot, mutoldc, mumolc, ...
    rhoc, dxblock, dyblock, u, v, epsold, TKEold, xnodel, ...
    ynodel, mueffc, ydist, dt, jin, kinlet)
%SOURCE TERM FOR K-EQUATION of k-epsilon model
    for i=2:(N_xtot-1)
        for j=2:(N_ytot-1)
            %Calculate Rate of strain tensors Sxy = Syx! Symmetrical!
            Sxx = (u(i,j) - u(i-1,j))/dxblock(i,j);
            Syy = (v(i,j) - v(i,j-1))/dyblock(i,j);
            Sxy = 1/2*(   ( 1/2*( (u(i,j+1)*dyblock(i,j)+...
                u(i,j)*dyblock(i,j+1))/...
                (dyblock(i,j+1)+dyblock(i,j)) +...
                    (u(i-1,j+1)*dyblock(i,j)+u(i-1,j)*dyblock(i,j+1))/...
                    (dyblock(i,j+1)+dyblock(i,j)) ) -...
                    1/2*( (u(i,j)*dyblock(i,j-1)+u(i,j-1)*dyblock(i,j))/...
                    (dyblock(i,j)+dyblock(i,j-1)) +...
                    (u(i-1,j)*dyblock(i,j-1)+u(i-1,j-1)*dyblock(i,j))/...
                    (dyblock(i,j)+dyblock(i,j-1)) ) )/dyblock(i,j) +...
                    ...
                    1/2*( (v(i+1,j)*dxblock(i,j)+v(i,j)*dxblock(i+1,j))/...
                    (dxblock(i+1,j)+dxblock(i,j)) +...
                    (v(i+1,j-1)*dxblock(i,j) + v(i,j-1)*dxblock(i+1,j))/...
                    (dxblock(i+1,j)+dxblock(i,j)) -...
                    (v(i,j)*dxblock(i-1,j)+v(i-1,j)*dxblock(i,j))/...
                    (dxblock(i,j)+dxblock(i-1,j)) -...
                    (v(i,j-1)*dxblock(i-1,j)+v(i-1,j-1)*dxblock(i,j))/...
                    (dxblock(i,j)+dxblock(i-1,j)) )/dxblock(i,j)   );
            Sxydom = 1/2*(( 1/2*( (u(i,j+1)*dyblock(i,j)+u(i,j)*dyblock(i,j+1))/...
                (dyblock(i,j+1)+dyblock(i,j)) +...
                    (u(i-1,j+1)*dyblock(i,j)+u(i-1,j)*dyblock(i,j+1))/...
                    (dyblock(i,j+1)+dyblock(i,j)) ) -...
                    1/2*( (u(i,j)*dyblock(i,j-1)+u(i,j-1)*dyblock(i,j))/...
                    (dyblock(i,j)+dyblock(i,j-1)) +...
                    (u(i-1,j)*dyblock(i,j-1)+u(i-1,j-1)*dyblock(i,j))/...
                    (dyblock(i,j)+dyblock(i,j-1)) ) )/dyblock(i,j));
                
            %k.1) Production rate of k!
            P_k = mutoldc(i,j)/rhoc*( 2*Sxx^2 + 2*Syy^2 + 4*Sxy^2);
            %P_k = mutoldc(i,j)/rhoc*(4*Sxydom^2);
            
            if(Geometry == 2 || Geometry == 3)
                SourceAxiSym = 1/(rhoc*ynodel(i,j))*mueffc(i,j)* ...
                    (TKEold(i,j+1)-TKEold(i,j-1))/(ynodel(i,j+1)-ynodel(i,j-1));
            else; SourceAxiSym = 0; end;
            
            %Launder-Sharma
            
%             if(j==N_ytot-1)
% %                 dsqrtkdy = 0.5*(TKEold(i,N_ytot-1)^(-1/2)*...
% %                     ((TKEold(i,N_ytot-1)*dyblock(i,N_ytot-2)+TKEold(i,N_ytot-2) ...
% %                     *dyblock(i,N_ytot-1)/(dyblock(i,N_ytot-1) + ...
% %                     dyblock(i,N_ytot-2)))-0)/dyblock(i,N_ytot-1);
% %                 D = 2*mumolc/rhoc*(dsqrtkdy^2);
% %                 Dmat(i,j) = D;
% %                 dsqrtkdy = 0.5*(TKEold(i,N_ytot-1)/2)^(-1/2)*...
% %                     (TKEold(i,N_ytot-1)-0)/ydist(i,N_ytot-1);
% %                 D = 2*mumolc/rhoc*(dsqrtkdy^2);
% %                 Dmat(i,j) = D;
%             else
                dsqrtkdy = 0.5*((TKEold(i,j+1)+TKEold(i,j-1))/2)^(-1/2)*...
                    (TKEold(i,j+1)-TKEold(i,j-1))/...
                    (dyblock(i,j+1)/2+dyblock(i,j)+dyblock(i,j-1)/2);
                D = 2*mumolc/rhoc*(dsqrtkdy^2);
                Dmat(i,j) = D;
%             end

            dsqrtkdy = 0.5*(TKEold(i,j))^(-1/2)*...
                ((TKEold(i,j)*dyblock(i,j-1)+TKEold(i,j-1)*dyblock(i,j)/(dyblock(i,j) ...
                + dyblock(i,j-1))) - ...
                (TKEold(i,j)*dyblock(i,j+1)+TKEold(i,j+1)*dyblock(i,j)/(dyblock(i,j) ...
                + dyblock(i,j))))/dyblock(i,j);
            D = 2*mumolc/rhoc*(dsqrtkdy^2);
            Dmat(i,j) = D;
            %Assembly
            STKmat(i-1,j-1) = P_k - D + TKEold(i,j)/dt + SourceAxiSym;
            
            if(i==2 && j <= jin) %checked! found mistake!
                STKmat(i-1,j-1) = STKmat(i-1,j-1) + ... 
                    (1/(rhoc*dxblock(i,j))*(mueffc(i,j)*dxblock(i-1,j) ...
                    + mueffc(i-1,j)*dxblock(i,j))/...
                    (dxblock(i,j)+dxblock(i-1,j))/ ...
                    (xnodel(i,j)-xnodel(i-1,j)) )*kinlet;
            end
        end
    end
    %Reshape
    Dmat(:,N_ytot) = Dmat(:, N_ytot-1); 
    Dmat(N_xtot,:) = Dmat(N_xtot-1,:); Dmat(:,1) = Dmat(:,2);
    STK = reshape(STKmat, (N_xtot-2)*(N_ytot-2),1);
end
